src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('objets/', include('objects.urls')),
]

if settings.DEBUG and settings.ENABLE_DJANGO_STATIC_SERVE:
    urlpatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

src/objects/forms.py
import re
import operator

from django import forms
from django.db.models import Q, F
from django.core.exceptions import ValidationError
from django.contrib.admin.widgets import FilteredSelectMultiple

from filters.models import Category, SubCategory, Color, Designer, Material, State, Style


class ObjectSearchForm(forms.Form):
    """Main form for search engine."""

    SUBCATEGORIES_QS = SubCategory.objects \
        .select_related('category') \
        .order_by('category__name', 'name')

    categories = forms.ModelMultipleChoiceField(
        label='Catégories',
        queryset=Category.objects.all(),
        to_field_name='slug',
        required=False,
        widget=forms.CheckboxSelectMultiple)
    subcategories = forms.ModelMultipleChoiceField(
        label='Catégories',  # Not a mistake
        queryset=SUBCATEGORIES_QS,
        to_field_name='slug',
        required=False,
         widget=forms.CheckboxSelectMultiple)
    is_negotiable = forms.BooleanField(
        label='prix négociable',
        required=False)
    price_min = forms.IntegerField(
        label='min',
        required=False)
    price_max = forms.IntegerField(
        label='max',
        required=False)
    designers = forms.ModelMultipleChoiceField(
        label="Designer",
        queryset=Designer.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple)
    state = forms.ModelMultipleChoiceField(
        label="état",
        queryset=State.objects.all(),
        to_field_name='slug',
        required=False,
        widget=forms.CheckboxSelectMultiple)
    materials = forms.ModelMultipleChoiceField(
        label="Matériaux",
        queryset=Material.objects.all(),
        to_field_name='slug',
        required=False,
        widget=forms.CheckboxSelectMultiple)
    style = forms.ModelMultipleChoiceField(
        label="Style",
        queryset=Style.objects.all(),
        to_field_name='slug',
        required=False,
        widget=forms.CheckboxSelectMultiple)
    colors = forms.ModelMultipleChoiceField(
        label='Couleurs',
        required=False,
        queryset=Color.objects.all(),
        widget=forms.CheckboxSelectMultiple)

    def filter_queryset(self, qs=None):
        """Filter querysets depending of input data."""

        if not self.is_bound:
            return qs

        # Populate cleaned_data
        if not hasattr(self, 'cleaned_data'):
            self.full_clean()

        is_negotiable= self.cleaned_data.get('is_negotiable', False)
        if is_negotiable:
            qs = qs.filter(is_negotiable=True)

        subcategories = self.cleaned_data.get('subcategories', None)
        if subcategories:
            qs = qs.filter(subcategories__in=subcategories)

        designers = self.cleaned_data.get('designers', None)
        if designers:
            qs = qs.filter(designer__in=designers)

        materials = self.cleaned_data.get('materials', None)
        if materials:
            qs = qs.filter(materials__in=materials)

        price_min = self.cleaned_data.get('price_min', 0)
        price_max = self.cleaned_data.get('price_max', None)
        if price_min or price_max:
            if not price_min:
                self.cleaned_data['price_min'] = 0
                price_min = self.cleaned_data['price_min']
                qs = qs.filter(price__range=(price_min, price_max))
            if not price_max:
                self.cleaned_data['price_max'] = 999999
                price_max = self.cleaned_data['price_max']
                qs = qs.filter(price__range=(price_min, price_max))
            else:
                qs = qs.filter(price__range=(price_min, price_max))

        state = self.cleaned_data.get('state', None)
        if state:
            qs = qs.filter(state__in=state)

        style = self.cleaned_data.get('style', None)
        if style:
            qs = qs.filter(style__in=style)

        colors = self.cleaned_data.get('colors', None)
        if colors:
            qs = qs.filter(colors__in=colors)

        # We filter by theme only if no categories were provided.
        # This is to handle the following edge case: on the multi-step search
        # form, the user selects a category, then on the last step, doesn't select
        # any subcategories and just click "Search".
        categories = self.cleaned_data.get('categories', None)
        if categories and not subcategories:
            qs = qs.filter(subcategories__categories__in=categories)

        return qs

src/templates/_checkbox_snippet.html
<div class="fr-input-group{% if field.field.required %} required{% endif %} checkbox mb-2">

    {% if nest_field_class %}
    <div class="{{ nest_field_class }}">
    {% endif %}

    {{ field }}

    {% if nest_field_class %}
    </div>
    {% endif %}

    <label for="{{ field.id_for_label }}" class="semi-bold uppercase font-size--s">{{ field.label }}</label>

    {% if field.help_text %}
        <span class="field-help">{{ field.help_text }}</span>
    {% endif %}

    {% if field.errors %}
    <p class="error field-error">
        ↑
        {{ field.errors.0 }}
        ↑
    </p>
    {% endif %}
</div>

src/templates/_field_snippet_collapse.html
<h2 class="accordion-header">
    <button class="accordion-button collapsed bg-inherit semi-bold uppercase font-size--s ps-0" type="button" data-bs-toggle="collapse" data-bs-target="#{{ field.name }}" aria-expanded="true" aria-controls="{{ field.name }}">
        {{ field.label }}
    </button>
</h2>

<div id="{{ field.name }}" class="accordion-collapse collapse" aria-labelledby="{{ field.name }}">
    <div id="form-group-{{ field.name }}" class="fr-input-group {% if field.field.required %}required{% endif %}">
        {% if field.help_text %}
        <span class="field-help">{{ field.help_text|safe }}</span>
        {% endif %}

        {% if nest_field_class %}
        <div class="{{ nest_field_class }}">
        {% endif %}

        {{ field }}

        {% if nest_field_class %}
        </div>
        {% endif %}

        {% if field.errors %}
        <p class="error field-error">
            ↑
            {{ field.errors.0 }}
            ↑
        </p>
        {% endif %}
    </div>
</div>

src/templates/_pagination.html
<div class="pagination justify-content-end">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; première</a>
            <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">suivante</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">dernière &raquo;</a>
        {% endif %}
    </span>
</div>

src/templates/_search_bar.html
{% load i18n %}

<form id="search-form" action="" method="get" autocomplete='off'>

    {{ form.apply_before.as_hidden }}

    <div class="">
        <div class="fr-col-12 fr-col-md-3">
            {% include '_field_snippet_collapse.html' with field=form.subcategories%}
        </div>

        <div class="pt-2 row col-12 px-0 pb-3">
            <label for="" class="semi-bold uppercase font-size--s pb-1">prix</label>
            <div id="form-group-price_min" class="col-6">
                <input type="number" name="price_min" value="" id="id_price_min" class="col-12">
                <label for="id_price_min" class="uppercase font-size--s">min</label>        
            </div>
            <div id="form-group-price_max" class="col-6">
                <input type="number" name="price_max" value="" id="id_price_max" class="col-12">
                <label for="id_price_max" class="uppercase font-size--s">max</label>        
            </div>
        </div>

        <div class="fr-col-12 fr-col-md-3 pt-2">
            {% include '_checkbox_snippet.html' with field=form.is_negotiable %}
        </div>

        <div class="fr-col-12 fr-col-md-3">
            {% include '_field_snippet_collapse.html' with field=form.designers %}
        </div>

        <div class="fr-col-12 fr-col-md-3">
            {% include '_field_snippet_collapse.html' with field=form.style %}
        </div>

        <div class="fr-col-12 fr-col-md-3">
            {% include '_field_snippet_collapse.html' with field=form.materials %}
        </div>

        <div class="fr-col-12 fr-col-md-3 mt-3">
            <div id="form-group-colors" class="fr-input-group ">
                <h2 class="semi-bold uppercase font-size--s ps-0 mb-4">couleurs</h2>
                <ul id="id_colors" class="d-flex justify-content-around flex-wrap me-5">
                {% for color in colors %}
                <li>
                    <label for="id_colors_{{ color.pk }}" class="checkbox">
                        <input name="colors" style="background-color:{{ color.code }}!important" type="checkbox" id="id_colors_{{ color.pk }}" value="{{ color.pk }}" title="{{ color.name }}">
                    </label>
                </li>
                {% endfor %}
                </ul>
            </div> 
        </div>

        <div class="fr-col-12 fr-col-md-3">
            {% include '_field_snippet_collapse.html' with field=form.state %}
        </div>
    </div>

    <button name="action" value="search-filter" class="green-btn btn border-radius--none mt-4 " type="submit">
        Filtrer les résultats
    </button>
</form>

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    {% block head-title %}
    <title>Lampes & Trouvailles</title>
    {% endblock %}
    <link rel="icon" type="images/png" href="/static/images/favicon.png" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" charset="utf-8">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    {% block extra_head %}
    <meta property="og:title" content="Lampes & Trouvailles" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Des lampes soigneusement chinées, du mobilier qui dure et des trouvailles remplies d'histoire" />
    <meta property="og:site_name" content="Lampes & Trouvailles" />
    <meta property="og:image" content="http://lampestrouvailles.eu.pythonanywhere.com/static/images/banner1-low.png" />
    <meta property="og:image:alt" content="Logo : Lampes & Trouvailles" />
    {% endblock %}

</head>

<body class="m-0">
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block js %}
{% endblock %} 
</body>
</html>

src/templates/footer.html
<footer class="py-5 border-top--black container px-0">
    <div class="row justify-content-start">
        <div class="col-12 col-md-3">
            <p class="semi-bold">Nos produits & services</p>
            <p><a href="{% url 'light-list' %}" class="text-reset">Lampes</a></p>
            <p><a href="{% url 'furniture-list' %}" class="text-reset">Mobilier</a></p>
            <p><a href="{% url 'finding-list' %}" class="text-reset">Trouvailles</a></p>
        </div>
        <div class="col-12 col-md-3">
            <p class="semi-bold">À propos</p>
            <p><a href="{% url 'about' %}" class="text-reset">Notre histoire</a></p>
            <p><a href="{% url 'contact' %}" class="text-reset">Nous contacter</a></p>
            <p><a href="{% url 'legal-mentions' %}" class="text-reset">Mentions légales</a></p>
        </div>
        <div class="col-12 col-md-3">
            <p class="semi-bold">Notre fonctionnement</p>
            <p><a href="{% url 'how' %}" class="text-reset">Paiement</a></p>
            <p><a href="{% url 'how' %}" class="text-reset">Livraisons et retraits</a></p>
            <p><a href="{% url 'how' %}" class="text-reset">Conditions générales</a></p>
        </div>
    </div>
    <div class="mt-5">
        <p class="small font-grey">© 2021 Lampes & Trouvailles</p>
    </div>
</footer>

src/templates/header.html
<header class="container px-0">
    <div class="d-flex justify-content-between align-items-center mb-5" id="desktop-header">
        <a href="{% url 'home' %}">
            <img src="/static/images/logo.svg" alt="" id="logo-desktop">
        </a>
        <nav class="px-5" id="nav-desktop">
            <a href="{% url 'light-list' %}">Lampes</a>
            <a href="{% url 'furniture-list' %}">Mobilier</a>
            <a href="{% url 'finding-list' %}">Trouvailles</a>
            <a href="{% url 'about' %}">À propos</a>
            <a href="{% url 'how' %}">Notre fonctionnement</a>
        </nav>
        <a href="{% url 'contact' %}" class="green-btn">Contact</a>
    </div>
    <div id="mobile-header">
        <div class="d-flex justify-content-between align-items-center my-3 mx-3">
            <a href="{% url 'home' %}">
                <img src="/static/images/logo_mobile.svg" alt="" id="logo-mobile">
            </a>
            <a id="togglemenu" onclick="document.body.classList.toggle('menuopen');">
                <span>
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </a>
        </div>
    </div>
    <nav class="px-5 my-5" id="menu">
        <a href="{% url 'light-list' %}">Lampes</a>
        <a href="{% url 'furniture-list' %}">Mobilier</a>
        <a href="{% url 'finding-list' %}">Trouvailles</a>
        <a href="{% url 'about' %}">À propos</a>
        <a href="{% url 'how' %}">Notre fonctionnement</a>
        <a href="{% url 'contact' %}">Contact</a>
    </nav>
</header>